---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: voting-app-route
spec:
  parentRefs:
    - name: voting-app-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ .Values.vote.serviceName }}
          port: {{ .Values.vote.targetPort }}

    - matches:
        - path:
            type: PathPrefix
            value: /result
      backendRefs:
        - name: {{ .Values.result.serviceName }}
          port: {{ .Values.result.targetPort }}